instagram/accounts/urls.py
from django.urls import path
from accounts import views
urlpatterns = [
    path('login/', views.reg,name='login'), 
    path('sign/', views.sign,name='sign'),
    path('logout/', views.logout_view,name='logout'),
    path('activate/<uidb64>/<token>/',views.activate)

]

instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('accounts/', include(('accounts.urls','accounts' ), namespace = 'accounts')),
    path('posts/', include(('post.urls', 'post' ), namespace = 'posts')),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/post/urls.py
from django.urls import path
from post import views
urlpatterns = [

    path("", views.home_view, name="home"),
    path("add/", views.add_post, name="add_post"),
    path("like/<post_id>/",views.like_toggle)
    ]

instagram/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class UserAccounts(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    phone = models.CharField(max_length=12)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O','Other')
    )
    is_verified = models.BooleanField(default=False)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    firstname = models.CharField(max_length=40,default='')
    lastname =models.CharField(max_length=40,default='')
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    objects = UserManager()

class Profile_picture(models.Model):
    user = models.OneToOneField(UserAccounts,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='profile',default='base.jpg')




# Create your models here.

instagram/accounts/forms.py
from .models import UserAccounts
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.forms import UserCreationForm


class Sign_up(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields=['email','firstname','lastname']   
    
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       
       del self.fields['password2']

instagram/accounts/views.py
from django.shortcuts import render,HttpResponse,redirect
from .forms import Sign_up
from django.views.generic import TemplateView, FormView
from django.contrib.auth import authenticate,login,logout,get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage


def reg(request):
    if request.method=='POST':
        email= request.POST['email']
        password= request.POST['password']
        user=authenticate(email=email,password=password)
        if user:
            if user.is_verified:
                login(request, user)
                return redirect('posts:home')
            else:
                return render(request, "accounts/register.html", {'error': True,
                 'error_msg': 'please verify your email address'})
        else:
            return render(request, "accounts/register.html", {'error': True,
            'error_msg': 'username or password is incorrect'})

    return render(request,'accounts/register.html')

def sign(request):
    if request.method=='POST':
        form = Sign_up(request.POST)
        user = form.save()
        generate_verification_email(user, request)
        return redirect('posts:home')
    form=Sign_up()
    return render(request,'accounts/signup.html',{'form':form})

def generate_verification_email(user, request):
    # token generation
    uid = urlsafe_base64_encode(force_bytes(user.pk))
    token = default_token_generator.make_token(user)
    current_site = get_current_site(request)

    message = f"verify email http://{current_site}/accounts/activate/{uid}/{token}/"

    email = EmailMessage('Insta verify email', message, to=[user.email])
    email.send()

    print(message)



# class Sign_up(FormView):
#     template_name = "accounts/signup.html"
#     form_class = Sign_up

#     def form_valid(self, form):
#         user = form.save()
#         generate_verification_email(user, self.request)
#         return redirect("/")

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = get_user_model().objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_verified = True
        user.save()
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')




# class RegisterView(FormView):
#     template_name = "accounts/register.html"
#     form_class = RegisterForm

#     def form_valid(self, form):
#         form.save()
#         return redirect("/")

def logout_view(request):
    logout(request)
    return redirect('accounts:login')

# Create your views here.

instagram/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    {% block css %}
    
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%  block content %}


    {% endblock %}
     
</body>
</html>

instagram/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{%  load static  %}
{% block css %}

    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/reg.css' %}">

{% endblock %}

{% block content %}

<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Overpass+Mono" rel="stylesheet">
<form action="" method='POST' >
    {% csrf_token %}
    <div class="main-content">
        <div class="header">
            <img src="https://i.imgur.com/zqpwkLQ.png" />
        </div>
        <div class="l-part">
            <input type="text" placeholder="Email" name ='email' class="input-1" />
            {{ form.username.errors }}
            <div class="overlap-text">
                <input type="password" placeholder="Password" name ='password' class="input-2" />
                {% if error %}
                <p style="color: red;">{{ error_msg }}</p>
                {% endif %}
                <a href="#">Forgot?</a><br>
            </div>
            <input type="submit" value="Log in" class="btn" />
        </div>
    </div>
 
    <div class="sub-content">
        <div class="s-part">
            Don't have an account?<a href="{% url 'accounts:sign' %}">Sign up</a>
        </div>
    </div>
</div>
</form>
{% endblock %}

instagram/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Halfmoon CSS -->
    <link href="https://cdn.jsdelivr.net/npm/halfmoon@1.1.1/css/halfmoon-variables.min.css" rel="stylesheet" />
    <!--
      Or,
      Use the following (no variables, supports IE11):
      <link href="https://cdn.jsdelivr.net/npm/halfmoon@1.1.1/css/halfmoon.min.css" rel="stylesheet" />
    -->
    
    <!-- Halfmoon JS -->
    <script src="https://cdn.jsdelivr.net/npm/halfmoon@1.1.1/js/halfmoon.min.js"></script>
</head>
<body>
    <center>
    <img src="https://i.imgur.com/zqpwkLQ.png" />
    <br>
    <form action="" method="POST" class="w-350  mw-full">
    
        {% load widget_tweaks %}

        {% csrf_token %}
        {% for fields in form.visible_fields %}
        <div class="form-group">
            {% render_field fields class="form-control" id="name" placeholder=fields.label required="required" %}
            <ul class="errorlist">
                {% for err in fields.errors %}
                <li>{{ err }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endfor %}
    
     
        <input class="w-350 btn btn-primary" type="submit" value="Sign up">
        <!-- {{ form.as_p }} -->
    
    </form>
</center>
</body>
</html>