instagram/accounts/urls.py
from django.urls import path
from accounts import views
urlpatterns = [
    path('login/', views.reg,name='login'), 
    path('sign/', views.sign,name='sign'),
    path('logout/', views.logout_view,name='logout'),
    path('activate/<uidb64>/<token>/',views.activate)

]

instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('accounts/', include(('accounts.urls','accounts' ), namespace = 'accounts')),
    path('posts/', include(('post.urls', 'post' ), namespace = 'posts')),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/post/urls.py
from django.urls import path
from post import views
urlpatterns = [

    path("", views.home_view, name="home"),
    path("add/", views.add_post, name="add_post"),
    path("like/<post_id>/",views.like_toggle)
    ]

instagram/post/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Post(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    caption = models.TextField()
    image = models.ImageField(upload_to='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    def liked_users(self):
        objects=Like.objects.filter(post=self).values_list('user',flat=True)
        return objects

class Like(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name='user_likes')
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='post_likes')
    class Meta:
        unique_together= ['user','post']
class Comment(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name='user_comment')
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='post_comment')
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

class Friends(models.Model):
    followers = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name='followers')
    following = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name='following')
    class Meta:
        unique_together = ['followers','following']
# Create your models here.

instagram/post/forms.py
from django import forms
from .models import Post

class PostAddForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image','caption']

instagram/post/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

from .forms import PostAddForm
from .models import Post, Like
# Create your views here.


@login_required
def home_view(request):
    posts = Post.objects.all().prefetch_related("post_likes").select_related("user")
    likes = Like.objects.filter(post__in=posts, user=request.user).values_list("post", flat=True)
    

    def is_liked_add(p):
        p.is_liked = p.id in likes
        print(p)
        return p

    posts = list(map(is_liked_add, posts))
    return render(request, "posts/home.html", {"posts": posts})



@login_required
def add_post(request):
    if request.method == 'POST':
        form = PostAddForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:home')
        else:
            return render(request, 'posts/add_post.html', {'form': form})
    else:
        form = PostAddForm()
        return render(request, 'posts/add_post.html', {'form': form})


def like_toggle(request, post_id):
    post = Post.objects.get(id=post_id)
    user = request.user
    response={}

    try:
        already_liked = Like.objects.get(post=post, user=user)
        already_liked.delete()
        response['status']='dislike'
    except Like.DoesNotExist:
        Like.objects.create(post=post, user=user)
        response['status']='like'
    response['count']=Like.objects.filter(post=post).count()
    return JsonResponse(response)
    


# Create your views here.

instagram/templates/posts/add_post.html
{% extends 'posts/base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="d-flex justify-content-center mt-0 mt-sm-20">
    <div class="w-full" style="max-width: 610px;">

        <!-- card -->
        <div class="bg-white border border-1 rounded mb-sm-20 p-20">

            <h5 class="font-weight-semi-bold">New Post</i></h5>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-10">
                    <label class="btn text-muted font-weight-medium" for="id_image">Choose Image</label>
                    {% render_field form.image class="form-control d-none" placeholder=form.image.label %}
                    <ul class="errorlist">
                        {% for err in form.image.errors %}
                        <li>{{ err }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="mb-10">
                    {% render_field form.caption class="form-control" placeholder='Write a caption...' %}
                    <ul class="errorlist">
                        {% for err in form.caption.errors %}
                        <li>{{ err }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <input type="submit" class="btn btn-primary" value="Post">
            </form>

        </div>

    </div>

    <!-- right-side-bar -->
    <div class="d-none d-lg-block position-relative"
        style="max-width: 290px;width: 290px; margin-left: 40px;z-index: 1;">
        <div class="position-fixed" style="width: inherit;margin-top: 2em;">
            <!-- userpic & name -->
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    <img class="border rounded-circle w-50 mr-10" src="{% static 'accounts/img/avatar.png' %}" alt="">
                    <div>
                        <div class="text-black font-weight-medium">designs.ui</div>
                        <div class="text-gray">ui/ux designs</div>
                    </div>
                </div>
                <button class="ico text-primary border-0 bg-transparent font-size-12 font-weight-medium">More</button>
            </div>

            <!-- suggestion -->
            <div class="d-flex justify-content-between align-items-center  mt-20 mb-15">
                <div class="text-muted font-size-14 font-weight-medium">
                    Suggestions For You
                </div>
                <button class="ico text-dark border-0 bg-transparent font-size-12 font-weight-medium">See All</button>
            </div>

            <div class="d-flex justify-content-between align-items-center mb-10">
                <div class="d-flex align-items-center">
                    <img style="width: 35px; height: 35px; object-fit: cover;" class="border rounded-circle mr-10"
                        src="https://images.unsplash.com/photo-1564048843342-6588968397ce?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=40&q=80"
                        alt="">
                    <div>
                        <div class="text-black font-weight-medium">picstay_kerala</div>
                        <div class="text-gray font-size-12">Suggested for you</div>
                    </div>
                </div>
                <button class="ico text-primary border-0 bg-transparent font-size-12 font-weight-medium">Follow</button>
            </div>

            <div class="d-flex justify-content-between align-items-center mb-10">
                <div class="d-flex align-items-center">
                    <img style="width: 35px; height: 35px; object-fit: cover;" class="border rounded-circle mr-10"
                        src="https://images.unsplash.com/photo-1574579991264-a87099cc17b1?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=40&q=80"
                        alt="">
                    <div>
                        <div class="text-black font-weight-medium">amazingdestination.z</div>
                        <div class="text-gray font-size-12">Popular</div>
                    </div>
                </div>
                <button class="ico text-primary border-0 bg-transparent font-size-12 font-weight-medium">Follow</button>
            </div>

            <div class="d-flex justify-content-between align-items-center mb-10">
                <div class="d-flex align-items-center">
                    <img style="width: 35px; height: 35px; object-fit: cover;" class="border rounded-circle mr-10"
                        src="https://images.unsplash.com/photo-1485206412256-701ccc5b93ca?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=42&q=80"
                        alt="">
                    <div>
                        <div class="text-black font-weight-medium">jacobelordi</div>
                        <div class="text-gray font-size-12">Popular</div>
                    </div>
                </div>
                <button class="ico text-primary border-0 bg-transparent font-size-12 font-weight-medium">Follow</button>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

instagram/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>

        {% block title %}
        Instagram
        {% endblock title %}

    </title>
    
        <script src="jquery-3.5.1.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  
    <link href="https://cdn.jsdelivr.net/npm/halfmoon@1.1.1/css/halfmoon-variables.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/halfmoon@1.1.1/js/halfmoon.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="{% static 'posts/style.css' %}">
    <link rel="shortcut icon" href="{% static 'accounts/img/favicon.ico' %}" />
</head>

<body>
    <!-- Navbar with a navbar-item as dropdown -->
    <div class="nav p-5 border-bottom 
    border-1 w-full d-flex justify-content-center
    position-fixed bg-white" style="z-index: 999;">
        <nav class="navbar border-0" style="width: 950px;">
            <!-- Navbar brand -->
            <a href="{% url 'posts:home' %}" class="navbar-brand">
                <img class="w-100 h-auto mt-10" src="{% static 'accounts/img/logo-text.png' %}" alt="...">
            </a>

            <!-- Inline form with input group -->
            <form class="form-inline ml-auto d-none d-sm-inline" action="..." method="...">
                <!-- ml-auto = margin-left: auto -->
                <div class="input-group">
                    <input type="text" class="form-control form-control-sm" placeholder="Search" required="required">

                </div>
            </form>

            <!-- Navbar nav -->
            <ul class="navbar-nav ml-auto">
                <!-- ml-auto = margin-left: auto -->
                <li class="nav-item">
                    <a href="{% url 'posts:home' %}" class="nav-link font-size-22 d-none d-sm-flex"><i
                            class="fas fa-home"></i></a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link font-size-20"><i class="far fa-paper-plane"></i></a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link font-size-22"><i class="far fa-heart"></i></a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" id="nav-link-dropdown-toggle">
                        <img class="rounded-circle w-25 border border-1" src="{% static 'accounts/img/avatar.png' %}"
                            alt="">
                        <i class="fa fa-angle-down ml-5" aria-hidden="true"></i>
                        <!-- ml-5= margin-left: 0.5rem (5px) -->
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="nav-link-dropdown-toggle">
                        <a href="{% url 'posts:add_post' %}" class="dropdown-item"><i
                                class="far fa-plus-square p-5 w-25 mr-5 font-size-16"></i>New Post</a>
                        <a href="#" class="dropdown-item"><i
                                class="far fa-user-circle p-5 w-25 mr-5 font-size-16"></i>Profile</a>
                        <a href="#" class="dropdown-item"><i
                                class="fas fa-cog p-5 w-25 mr-5 font-size-16"></i>Settings</a>
                        <a href="#" class="dropdown-item"><i
                                class="far fa-bookmark p-5 w-25 mr-5 font-size-16"></i>Saved</a>


                        <div class="dropdown-divider"></div>
                        <a href="{% url 'accounts:logout' %}" class="dropdown-item">Log Out</a>
                    </div>
                </li>
            </ul>
        </nav>
    </div>
    <div class="w-full d-flex justify-content-center" style="background-color: #fafafa;">
        <div class="" style="width: 950px;margin-top: 60px;">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>

</html>

instagram/templates/posts/home.html
{% extends 'posts/base.html' %}

{% load static %}

{% block content %}
<div class="d-flex justify-content-center mt-0 mt-sm-20">
    <div class="w-full" style="max-width: 610px;">
        <!-- posts -->

        {% for post in posts %}
        <div class="bg-white border border-1 rounded mb-sm-20">

            <!-- post title -->
            <div style="height: 60px;" class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    <img class="border rounded-circle mx-15" style="width: 35px; height: 35px; object-fit: cover;"
                        src="https://images.unsplash.com/photo-1611615842525-6c2adb767846?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=40&q=80"
                        alt="">
                    <div>
                        <p class="m-0 font-size-14 font-weight-medium">{{ post.user.first_name }}</p>
                        <p class="m-0 font-size-12">Heaven</p>
                    </div>
                </div>
                <div class="mx-15">
                    <img style="width: 15px;" src="{% static 'posts/menu.svg' %}" alt="">
                </div>
            </div>

            <!-- post image -->
            <img class="w-full" src="{{ post.image.url }}" alt="">

            <!-- post footer -->
            <div class="mx-10 px-5 my-5">

                <!-- post button -->
                <div class="d-flex justify-content-between">
                    <div>
                        <button data-id="{{ post.id }}" class="like-btn ico {% if post.is_liked %} text-danger  {% endif %} pl-0 border-0 bg-transparent font-size-22">
                            <i class="{% if post.is_liked %}
                                    fas {% else %} far {% endif %} fa-heart  "></i></button>
                        <button class="ico text-dark border-0 bg-transparent font-size-22"><i
                                class="far fa-comment"></i></button>
                        <button class="ico text-dark border-0 bg-transparent font-size-22"><i
                                class="far fa-paper-plane"></i></button>
                    </div>
                    <div>
                        <button class="ico text-dark border-0 bg-transparent font-size-22"><i
                                class="far fa-bookmark"></i></button>
                    </div>
                </div>

                <!-- post likes -->
                <p class="my-5 font-weight-semi-bold text-dark">{{ post.post_likes.count }} likes</p>

                <!-- post user and description -->
                <div>
                    <p class="my-0 text-dark d-inline-block">
                        <span class="font-weight-semi-bold ">{{ post.user.first_name }}</span>
                        <span class="">
                            {{ post.caption }}
                        </span>
                    </p>
                </div>

                <!-- comments -->
                <span class="text-gray font-size-14">View all 17 comments</span>

                <div>
                    <div class="mt-5">
                        <p class="my-0 text-dark d-inline-block">
                            <span class="font-weight-semi-bold ">jishad_kp_</span>
                            <span class="">
                                anak vere paniyonnum ille😂😂😂#memes follow @norulesmake.up
                                Follow @norulesmake.up tag @norulesmake.up to get featured
                            </span>
                        </p>
                    </div>
                    <div class="mt-5">
                        <p class="my-0 text-dark d-inline-block">
                            <span class="font-weight-semi-bold ">sara_begou</span>
                            <span class="">
                                @juju_brds ptdr moi la dernière fois à Pau
                            </span>
                        </p>
                    </div>
                </div>
                <!-- end comments -->

                <!-- published time -->
                <div style="font-size: 10px;" class="text-uppercase mt-5 mb-10 text-gray">3 days ago</div>


            </div>

            <div class="d-none d-sm-block">
                <hr>
            </div>
            <!-- new comment -->
            <div class="d-none d-sm-flex mx-10 px-5 h-50">
                <button style="font-size: 24px;" class="ico text-dark pl-0 mr-5 border-0
                                   bg-transparent">
                    <i class="far fa-smile"></i>
                </button>
                <input class="d-block w-full ico border-0" placeholder="Add a comment..." type="text">
                <button class="ico text-primary pl-0 border-0 bg-transparent font-weight-medium">Post</button>
            </div>

        </div>

        {% endfor %}



    </div>

    <!-- right-side-bar -->
    <div class="d-none d-lg-block position-relative"
        style="max-width: 290px;width: 290px; margin-left: 40px;z-index: 1;">
        <div class="position-fixed" style="width: inherit;margin-top: 2em;">
            <!-- userpic & name -->
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    <img class="border rounded-circle w-50 mr-10" src="{% static 'accounts/avatar.png' %}" alt="">
                    <div>
                        <div class="text-black font-weight-medium">Sahad_Mukkam</div>
                        <div class="text-gray">Sahad_Mukkam</div>
                    </div>
                </div>
                <button class="ico text-primary border-0 bg-transparent font-size-12 font-weight-medium">More</button>
            </div>

            <!-- suggestion -->
            <div class="d-flex justify-content-between align-items-center  mt-20 mb-15">
                <div class="text-muted font-size-14 font-weight-medium">
                    Suggestions For You
                </div>
                <button class="ico text-dark border-0 bg-transparent font-size-12 font-weight-medium">See All</button>
            </div>

            <div class="d-flex justify-content-between align-items-center mb-10">
                <div class="d-flex align-items-center">
                    <img style="width: 35px; height: 35px; object-fit: cover;" class="border rounded-circle mr-10"
                        src="https://images.unsplash.com/photo-1564048843342-6588968397ce?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=40&q=80"
                        alt="">
                    <div>
                        <div class="text-black font-weight-medium">zalu_salman</div>
                        <div class="text-gray font-size-12">Suggested for you</div>
                    </div>
                </div>
                <button class="ico text-primary border-0 bg-transparent font-size-12 font-weight-medium">Follow</button>
            </div>

            <div class="d-flex justify-content-between align-items-center mb-10">
                <div class="d-flex align-items-center">
                    <img style="width: 35px; height: 35px; object-fit: cover;" class="border rounded-circle mr-10"
                        src="https://images.unsplash.com/photo-1574579991264-a87099cc17b1?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=40&q=80"
                        alt="">
                    <div>
                        <div class="text-black font-weight-medium">jamsheer_koniyath</div>
                        <div class="text-gray font-size-12">Popular</div>
                    </div>
                </div>
                <button class="ico text-primary border-0 bg-transparent font-size-12 font-weight-medium">Follow</button>
            </div>

            <div class="d-flex justify-content-between align-items-center mb-10">
                <div class="d-flex align-items-center">
                    <img style="width: 35px; height: 35px; object-fit: cover;" class="border rounded-circle mr-10"
                        src="https://images.unsplash.com/photo-1485206412256-701ccc5b93ca?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=42&q=80"
                        alt="">
                    <div>
                        <div class="text-black font-weight-medium">mahshook_katt</div>
                        <div class="text-gray font-size-12">Popular</div>
                    </div>
                </div>
                <button class="ico text-primary border-0 bg-transparent font-size-12 font-weight-medium">Follow</button>
            </div>

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.like-btn').click(function () {
            var id =$(this).data('id')
            var icon =$(this).children('i')
            var btn =$(this)

        
        $.ajax(`/posts/like/${id}/`,{
                method:'GET',
                processData:false,
                contentType:false,
                success(response){
                    if(response.status=='like'){
                        icon.removeClass('far')
                        icon.addClass('fas')
                        btn.addClass('text-danger')
                        

                    }
                    else if(response.status=='dislike'){
                        icon.removeClass('fas')
                        icon.addClass('far')
                        btn.removeClass('text-danger')

                    }
                
                    btn.parent().parent().next().text(response.count+' likes')    

                },
                error(){

                },

            })

        });
    });
    
</script>
{% endblock content %}